# Generated by Django 3.2 on 2021-05-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0002_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainPort', models.IntegerField()),
                ('subPort', models.IntegerField()),
                ('deviceName', models.CharField(max_length=16)),
                ('deviceSpeed', models.CharField(max_length=16)),
                ('deviceBus', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to=''),
        ),
    ]
